loan_default_prediction:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
      user: "{{ env_var('POSTGRES_USER', 'loan_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'loan_password') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'loan_default') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public,raw,staging,intermediate,marts
